feat: Add GitHub Actions workflow for backend deployment to Ubuntu server.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,14 +34,14 @@ jobs:
       - name: Network Diagnostics
         run: |
           echo "Pinging host..."
-          ping -c 1 marcostorresalarcon.com || echo "Ping failed"
+          ping -c 1 ssh.marcostorresalarcon.com || echo "Ping failed"
           echo "Testing SSH port connectivity..."
-          nc -zv marcostorresalarcon.com 22
+          nc -zv ssh.marcostorresalarcon.com 22
 
       - name: Deploy to Ubuntu Server via SSH
         uses: appleboy/ssh-action@v1.0.3
         with:
-          host: marcostorresalarcon.com
+          host: ssh.marcostorresalarcon.com
           username: marcostor13
           password: ${{ secrets.SERVER_PASSWORD }}
           port: 22
